### ISSUE TITLE
[consult][feature] Is there graph save and load API?

### ISSUE THREAD

**Issue by littleDrew** [alibaba/graph-learn#191]
**hi buddy, i want to know if there are api for saving and loading graph in graphlearn** ? 
> like `dgl` save/load and `PGL` dump/load interface

- if currently there is no such api, what's the roughly implement way/mind that implement save/load ? hoping for your sharing~
- how will the save format been considered ?

**Comment by baoleai** [comment]
Hi, GL doesn't  support saving graph. Graph Loading API is in https://graph-learn.readthedocs.io/en/latest/graph/graph_object.html . 
Graph storage is implemented in C++, and rocksdb can be considered for saving graph data.

**Comment by littleDrew** [comment]
yeah, thanks, i have other question want to consult : )

- **first question** here i see graph-learn seems aim to do graph-computation in large graph, can this obtained good performance in small but large amout of graph? 
  - > like in dgl graph classfication documentation: https://docs.dgl.ai/guide/training-graph.html
  - here in graph-learn, graph is stored in c++ layer, and there might no need to do sample for small graph, but when training, data of graph need be passing(copy) into python layer, this may take some time comparing with dgl(which store data in python layer)
- **another question**: here i see in other material, it refers graph-learn will be integrated into graphscope, is that so ?
  - in that meterial, here refers the support dynamic and efficient graph storage, will above mentioned rocksdb be okay to do so or any good ideas(as i see graph-learn didn't release new feature for quite long time), there are some reading performance of rockdb here.

**Comment by baoleai** [comment]
Good questions! 
1. Graph-Learn is mainly aim to large-scale graph learning because it is challenging to train a GNN model efficiently on large-scale graphs. For small graphs training, we don't need sample neighbors anymore, therefore, we did not consider the optimization on small graphs before, but we will do some parallel optimization on small graph training later.
2. Yes, Graph-Learn is already integrated into GraphScope. The current version of GL is only support static graph, the dynamic graph part will be released in a few weeks and it uses rocksdb indeed.
