### ISSUE TITLE
Save embeddings issue when distributed training

### ISSUE THREAD

**Issue by ming-ch** [alibaba/graph-learn#53]
Hi,

I run the dist_trian.py (examples/tf/graphsage/dist_train.py), it works well. However, when I try to save embedding after training, it raises RuntimeError("Graph is finalized and cannot be modified."). I meet the same issue when I try to run Bipartite GraphSAGE in the distribute mode.

```
  Traceback (most recent call last):
  File "dist_train.py", line 132, in <module>
    main()
  File "dist_train.py", line 128, in main
    train(config, g)
  File "dist_train.py", line 81, in train
    u_embs = trainer.get_node_embedding("u")
  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/model/tf/trainer.py", line 57, in get_node_embedding
    ids, emb, iterator = self.model.node_embedding(node_type)
```

**Comment by amznero** [comment]
The same problem happened to me a few days ago. I guess the problem may be caused by the `MonitoredTrainingSession `(MTS, for short).

`graph-learn` uses [MonitoredTrainingSession](https://github.com/alibaba/graph-learn/blob/master/graphlearn/python/model/tf/trainer.py#L219-L221) for init ps(distributed mode in TensorFlow) environment.

But MTS will **freeze** the **TF Graph(not GNN)** after the initialization step is completed. So users are **not allowed** to modify the graph(can't define some new variable/op).

For this issue, after we use [trainer.py](https://github.com/alibaba/graph-learn/blob/master/graphlearn/python/model/tf/trainer.py) to init the session, the TF Graph will be frozen, then the model begins to train for n epochs. (No modify here). But when the code goes to save embedding, it will register a new variable for getting source nodes' embeddings(try to modify the TF graph, then raise an error). 

For me, I made some modifications to [graph_sage.py](https://github.com/alibaba/graph-learn/blob/master/examples/tf/graphsage/graph_sage.py).

```python
def build(self):
  ...
  pos_src_emb = self.encoders['src'].encode(self.pos_src_ego_tensor)
  pos_dst_emb = self.encoders['dst'].encode(self.pos_dst_ego_tensor)
  neg_dst_emb = self.encoders['dst'].encode(self.neg_dst_ego_tensor)
  
  # some modifications
  self.pos_src_emb = pos_src_emb
  self.pos_dst_emb = pos_dst_emb
  self.neg_dst_emb = neg_dst_emb

  self.loss = self._unsupervised_loss(pos_src_emb, pos_dst_emb, neg_dst_emb)
  ...

...

def node_embedding(self, type):
  iterator = self.ego_flow.iterator
  # remove
  # ego_tensor = self.ego_flow.pos_src_ego_tensor
  # remove
  # src_emb = self.encoders['src'].encode(ego_tensor)
  # add
  src_emb = self.pos_src_emb
  src_ids = self.pos_src_ego_tensor.src.ids
  return src_ids, src_emb, iterator

...

```

---

Similary issue on [StackOverflow](https://stackoverflow.com/a/41798401).

**Comment by baoleai** [comment]
The `get_node_embedding` in trainer.py is only for local training mode now. For distributed training, there is indeed a problem like @amznero said, you can put `get_node_embedding` in `train` funciton before session run in trainer.py. There may be a more elegant solution, I will fix it asap:)
