### ISSUE TITLE
classical graph algorithms examples

### ISSUE THREAD

**Issue by patricxu** [alibaba/graph-learn#57]
Could you give us a few examples for the classical graph algorithms, such as Pagerank, LPA, WCC, etc.?

**Comment by jackonan** [comment]
GL aims for GNN instead of classical graph algorithms, such as PageRank. So we did not show examples in this field. GL abstracts a `Partition-Process-Stitch` framework, which looks like `Map-Reduce` and covers a lot of computing pattern. All of the `Samplers` are implemented based on this framework. Maybe you can have a try.

**Comment by patricxu** [comment]
It's worth a try!
