### ISSUE TITLE
Do you have any references on Bipartite GraphSage?

### ISSUE THREAD

**Issue by hibayesian** [alibaba/graph-learn#59]
Do you have any references on Bipartite GraphSage? What's the differences between Bipartite GraphSage and classical GraphSage?

**Comment by jackonan** [comment]
`Bipartite GraphSage` is a typical usage of `GraphSage` theory on heterogeneous graph. In more practical cases, graph data is heterogeneous rather than homogeneous. To extend the classical `GraphSage` is a natural choice. 

We did not release any paper about this topic. You can refer our code for details.
