### ISSUE TITLE
Do graph-learn's client and server correspond to PS and jobs in TensorFlow?

### ISSUE THREAD

**Issue by Zdm-Jdsc-lalala** [alibaba/graph-learn#73]
What are the roles of client and server？
About deploy_ Mode: 
what is 2 considered relative to 0 and 1

Thank you for the answer！

**Comment by Seventeen17** [comment]
**Server** in GraphLearn is where the Graph stored, and it responds to the graph query requests.
**Client** in GraphLearn is who raises the query requests, and holds the responses.
Servers and Clients are not limited of being deployed on which machine. 
Deploy Mode 0 is local mode, server and client are on a same machine.
Deploy Mode 1 is independent distribute mode, it means servers and client are independent, for example, servers are deployed along with Tensorflow PSs, clients are deployed with Tenorflow workers, so that the samples parsed from the responses and the trainer with the samples are on the same machine.
Deploy Mode 2 is in-memory deistribute mode, it means one server is deployed with one client, and the total number of servers is same with clients.
